import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { AttendanceRecord, Task } from '../types';

export const generateAttendancePDF = (logs: AttendanceRecord[], userName: string, month: string) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(28);
  doc.setTextColor(37, 99, 235); // Brand Primary (Blue 600)
  doc.text('LIGHTYEAR', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('AGENCY STUDIO - MISSION REPORT', 14, 28);
  
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text(`Attendance Summary: ${month}`, 14, 45);
  doc.text(`Generated by: ${userName}`, 14, 52);
  doc.text(`Date: ${format(new Date(), 'PPPP')}`, 14, 59);

  const tableData = logs.map(log => [
    format(log.timestamp?.toDate() || new Date(), 'dd MMM yyyy'),
    format(log.timestamp?.toDate() || new Date(), 'pp'),
    log.userName,
    log.type.toUpperCase(),
    log.location ? `${log.location.latitude.toFixed(4)}, ${log.location.longitude.toFixed(4)}` : 'N/A'
  ]);

  autoTable(doc, {
    startY: 70,
    head: [['Date', 'Time', 'User', 'Action', 'Coordinates']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 8 }
  });

  doc.save(`Attendance_Report_${month}_${userName.replace(/\s/g, '_')}.pdf`);
};

export const generateTasksPDF = (tasks: Task[], userName: string, period: string) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(28);
  doc.setTextColor(37, 99, 235);
  doc.text('LIGHTYEAR', 14, 22);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text('AGENCY STUDIO - OPERATIONAL TASKS', 14, 28);
  
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text(`Task Progress Report: ${period}`, 14, 45);
  doc.text(`Generated by: ${userName}`, 14, 52);

  const tableData = tasks.map(task => [
    task.title,
    task.assignedToName,
    `${task.progress}%`,
    task.status.toUpperCase(),
    format(task.deadline?.toDate() || new Date(), 'dd MMM yyyy')
  ]);

  autoTable(doc, {
    startY: 65,
    head: [['Objective', 'Assigned To', 'Progress', 'Status', 'Deadline']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 8 }
  });

  doc.save(`Tasks_Report_${period}_${userName.replace(/\s/g, '_')}.pdf`);
};
